//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeFortune.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokeFortune.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über PokeFortune.
        /// </summary>
        public static string AboutPokeFortune {
            get {
                return ResourceManager.GetString("AboutPokeFortune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achte Generation.
        /// </summary>
        public static string EighthGen {
            get {
                return ResourceManager.GetString("EighthGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        public static string Favourite {
            get {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fünfte Generation.
        /// </summary>
        public static string FifthGen {
            get {
                return ResourceManager.GetString("FifthGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Generation.
        /// </summary>
        public static string FirstGen {
            get {
                return ResourceManager.GetString("FirstGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vierte Generation.
        /// </summary>
        public static string FourthGen {
            get {
                return ResourceManager.GetString("FourthGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendäre.
        /// </summary>
        public static string Legendary {
            get {
                return ResourceManager.GetString("Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionen.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon.
        /// </summary>
        public static string Pokemon {
            get {
                return ResourceManager.GetString("Pokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zweite Generation.
        /// </summary>
        public static string SecondGen {
            get {
                return ResourceManager.GetString("SecondGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siebte Generation.
        /// </summary>
        public static string SeventhGen {
            get {
                return ResourceManager.GetString("SeventhGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiny-Modus.
        /// </summary>
        public static string ShinyMode {
            get {
                return ResourceManager.GetString("ShinyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sechste Generation.
        /// </summary>
        public static string SixthGen {
            get {
                return ResourceManager.GetString("SixthGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dritte Generation.
        /// </summary>
        public static string ThirdGen {
            get {
                return ResourceManager.GetString("ThirdGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation.
        /// </summary>
        public static string Transformation {
            get {
                return ResourceManager.GetString("Transformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käfer.
        /// </summary>
        public static string Type_Bug {
            get {
                return ResourceManager.GetString("Type_Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlicht.
        /// </summary>
        public static string Type_Dark {
            get {
                return ResourceManager.GetString("Type_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drache.
        /// </summary>
        public static string Type_Dragon {
            get {
                return ResourceManager.GetString("Type_Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektro.
        /// </summary>
        public static string Type_Electric {
            get {
                return ResourceManager.GetString("Type_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string Type_Fairy {
            get {
                return ResourceManager.GetString("Type_Fairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampf.
        /// </summary>
        public static string Type_Fighting {
            get {
                return ResourceManager.GetString("Type_Fighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feuer.
        /// </summary>
        public static string Type_Fire {
            get {
                return ResourceManager.GetString("Type_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flug.
        /// </summary>
        public static string Type_Flying {
            get {
                return ResourceManager.GetString("Type_Flying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geist.
        /// </summary>
        public static string Type_Ghost {
            get {
                return ResourceManager.GetString("Type_Ghost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pflanze.
        /// </summary>
        public static string Type_Grass {
            get {
                return ResourceManager.GetString("Type_Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boden.
        /// </summary>
        public static string Type_Ground {
            get {
                return ResourceManager.GetString("Type_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eis.
        /// </summary>
        public static string Type_Ice {
            get {
                return ResourceManager.GetString("Type_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Type_Normal {
            get {
                return ResourceManager.GetString("Type_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift.
        /// </summary>
        public static string Type_Poison {
            get {
                return ResourceManager.GetString("Type_Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psycho.
        /// </summary>
        public static string Type_Psychic {
            get {
                return ResourceManager.GetString("Type_Psychic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestein.
        /// </summary>
        public static string Type_Rock {
            get {
                return ResourceManager.GetString("Type_Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stahl.
        /// </summary>
        public static string Type_Steel {
            get {
                return ResourceManager.GetString("Type_Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasser.
        /// </summary>
        public static string Type_Water {
            get {
                return ResourceManager.GetString("Type_Water", resourceCulture);
            }
        }
    }
}
